👷 Use CI for Status Check Before Merging
* 🩹 Rename job in test python workflow

* 👷 Add CI aggregating job

* 👷 Add check if draft pull request

* 👷 Add skipped job check in CI aggregator

* 👷 Remove skipped from ci aggregator needs checks

* 👷 Add pull request types to ci trigger

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,6 +8,7 @@ on:
   pull_request:
     branches:
       - main
+    types: [opened, synchronize, reopened, ready_for_review]
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
@@ -18,10 +19,12 @@ jobs:
     uses: ./.github/workflows/pre-commit.yml
     with:
       python-version: '3.9'
+    if: ${{ !github.event.pull_request.draft }}
 
   lint-rust:
     needs: pre-commit
     uses: ./.github/workflows/check-rust.yml
+    if: ${{ !github.event.pull_request.draft }}
 
   python-static-checks:
     needs: pre-commit
@@ -31,11 +34,28 @@ jobs:
         python-version: ['3.9', '3.13']
     with:
       python-version: ${{ matrix.python-version }}
+    if: ${{ !github.event.pull_request.draft }}
 
   test-rust:
     needs: [pre-commit, lint-rust]
     uses: ./.github/workflows/test-rust.yml
+    if: ${{ !github.event.pull_request.draft }}
 
   test-python:
     needs: [pre-commit, lint-rust, python-static-checks]
     uses: ./.github/workflows/test-python.yml
+    if: ${{ !github.event.pull_request.draft }}
+
+  ci:
+    name: CI
+    needs: [pre-commit, lint-rust, python-static-checks, test-rust, test-python]
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    steps:
+      - name: Check all jobs passed
+        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        run: |
+          echo "One or more required jobs failed or were cancelled."
+          exit 1
+      - name: All checks passed
+        run: echo "All checks passed successfully!"
